# Generated by Django 5.2.6 on 2025-09-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_colour', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
